name: auto_deploy

inputs:
  package:
    required: true
  gcp_region:
    required: true
  gcp_project_id:
    required: true
  gcp_service_account_key:
    required: true
  server_uri:
    required: true
  x-api-key:
    required: false

runs:
  using: composite
  steps:
    - name: Authenticate with Google Cloud
      id: authenticate_with_google_cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.gcp_service_account_key }}

    - name: Configure Google Cloud
      id: configure_google_cloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      id: configure_docker
      run: |
        gcloud auth configure-docker ${{inputs.gcp_region}}-docker.pkg.dev
      shell: bash

    - name: Docker Build and Push Image
      id: docker_build_and_push_image
      run: |
        IMAGE_NAME="${{inputs.gcp_region}}-docker.pkg.dev/${{inputs.gcp_project_id}}/monorepo-${{inputs.package}}/deploy"

        docker build \
          --build-arg NEXT_PUBLIC_SERVER_URI=${{ inputs.server_uri }} \
          --build-arg NEXT_PUBLIC_VALIDATED_API_KEY=${{ inputs.x-api-key }} \
          -t $IMAGE_NAME:latest -f apps/${{inputs.package}}/Dockerfile .
          
        docker push $IMAGE_NAME:latest
      shell: bash

    - name: Deploy to Cloud Run
      id: deploy_to_cloud_run
      run: |
        gcloud run deploy ${{inputs.package}} \
          --image=${{inputs.gcp_region}}-docker.pkg.dev/${{inputs.gcp_project_id}}/monorepo-${{inputs.package}}/deploy:latest \
          --region=${{inputs.gcp_region}} \
          --platform=managed \
          --allow-unauthenticated
      shell: bash
