import {
  YarnBerryPnp,
  GithubActions1,
  GithubActions2,
  GithubActions3,
  YarnWorkspaceMonorepo1,
  YarnWorkspaceMonorepo2,
  YarnWorkspaceMonorepo3,
  YarnWorkspaceMonorepo4,
  YarnWorkspaceMonorepo5,
  Msw1,
  Msw2,
  Msw3,
  WoowaTechCourse,
  MarchMemoir,
  FastestVite,
  NextMigration1,
  NextMigration2,
  NextMigration3,
  NextMigration4,
  AIGithubActions,
} from "@images";

export const BLOG_THUMBNAIL: {
  [key: string]: React.FC<React.SVGProps<SVGSVGElement>>;
} = {
  "march-memoir": MarchMemoir,
  "woowa-course": WoowaTechCourse,
  "msw-3": Msw3,
  "msw-2": Msw2,
  "msw-1": Msw1,
  "yarn-workspace-monorepo-5": YarnWorkspaceMonorepo5,
  "yarn-workspace-monorepo-4": YarnWorkspaceMonorepo4,
  "yarn-workspace-monorepo-3": YarnWorkspaceMonorepo3,
  "yarn-workspace-monorepo-2": YarnWorkspaceMonorepo2,
  "yarn-workspace-monorepo-1": YarnWorkspaceMonorepo1,
  "github-actions-3": GithubActions3,
  "github-actions-2": GithubActions2,
  "github-actions-1": GithubActions1,
  "yarn-berry-pnp-1": YarnBerryPnp,
  "fastest-vite": FastestVite,
  "next-migration-1": NextMigration1,
  "next-migration-2": NextMigration2,
  "next-migration-3": NextMigration3,
  "next-migration-4": NextMigration4,
  AIGithubActions: AIGithubActions,
};
