# ! portfolio 패키지의 cd 진행
# ! build 체크 및 버저닝

name: portfolio_cd

on:
  workflow_call:

env:
  NEXT_PUBLIC_SERVER_URI: ${{secrets.NEXT_PUBLIC_SERVER_URI}}
  NEXT_PUBLIC_VALIDATED_API_KEY: ${{secrets.NEXT_PUBLIC_VALIDATED_API_KEY}}

jobs:
  integration:
    name: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Auto Deploy
        id: auto_deploy
        uses: ./.github/actions/auto_deploy
        with:
          package: "portfolio"
          gcp_region: ${{ secrets.GCP_REGION }}
          gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
          gcp_service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          server_uri: ${{ secrets.NEXT_PUBLIC_SERVER_URI }}
          x-api-key: ${{secrets.NEXT_PUBLIC_VALIDATED_API_KEY}}

      - name: Upload Log File
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: workflow_logs
          path: log_${{ github.run_id }}.txt
          if-no-files-found: error
          retention-days: 1
