# ! portfolio 패키지의 ci 진행
# ! 의존성 설치 및 빌드 진행

name: portfolio_ci

on:
  workflow_call:

env:
  NEXT_PUBLIC_SERVER_URI: ${{secrets.NEXT_PUBLIC_SERVER_URI}}
  NEXT_PUBLIC_VALIDATED_API_KEY: ${{secrets.NEXT_PUBLIC_VALIDATED_API_KEY}}

jobs:
  integration:
    name: integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: git_checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node
        id: setup_node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        id: setup_pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install dependency
        id: install_dependency
        run: |
          pnpm install --frozen-lockfile 2> >(tee log_${{ github.run_id }}.txt) ; \
          test ${PIPESTATUS[0]} -eq 0 || { echo "pnpm install failed." ; exit 1; }

      - name: Run Build
        id: run_build
        run: |
          pnpm build --filter=portfolio 2> >(tee test_log) ; \
          test ${PIPESTATUS[0]} -eq 0 || { echo "pnpm portfolio build failed." ; exit 1; }

      - name: Upload Log File
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: workflow_logs
          path: log_${{ github.run_id }}.txt
          if-no-files-found: error
          retention-days: 1
